# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosreact725' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosreact725
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'
  pod 'MobileCenter'
  pod 'MobileCenter/Crashes'
  pod 'MobileCenter/Analytics'
  pod 'MobileCenter/Push'
  
  end


  

  target 'iosreact725Tests' do
    inherit! :search_paths
    # Pods for testing

end

target 'iosreact725-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosreact725-tvOS
end
  target 'iosreact725-tvOSTests' do
    inherit! :search_paths


end
